In [19]:
import numpy as np


In [20]:
import numpy as np
X = np.array([[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1] ])
y = np.array([[0,1,1,0,1,0,0,1]]).T
z = np.array([[0,0,0,1,0,1,1,1]]).T
syn0 = 2*np.random.random((3,4)) - 1
print(syn0)
syn1 = 2*np.random.random((4,1)) - 1
print(syn1)
syn3 = 2*np.random.random((3,4)) - 1
print(syn0)
syn4 = 2*np.random.random((4,1)) - 1
print(syn1)
#Neural network with Z variable as target
for j in range(60000):
  #feed forward with sigmoid activation for first layer
  l1 = 1/(1+np.exp(-(np.dot(X,syn0))))
  #feed forward with sigmoid activation for first layer
  l2 = 1/(1+np.exp(-(np.dot(l1,syn1))))
  l2_delta = (y - l2)*(l2*(1-l2))
  l1_delta = l2_delta.dot(syn1.T) * (l1 * (1-l1))
  syn1 += l1.T.dot(l2_delta)
  syn0 += X.T.dot(l1_delta)
# Neural network with Z variable as target
for k in range(60000):
  #feed forward with sigmoid activation for first layer
  l3 = 1/(1+np.exp(-(np.dot(X,syn3))))
  #feed forward with sigmoid activation for first layer
  l4 = 1/(1+np.exp(-(np.dot(l3,syn4))))
  l4_delta = (z - l4)*(l4*(1-l4))
  l3_delta = l4_delta.dot(syn4.T) * (l3 * (1-l3))
  syn4 += l3.T.dot(l4_delta)
  syn3 += X.T.dot(l3_delta)

  #feed forward with sigmoid activation for first layer
  l1 = 1/(1+np.exp(-(np.dot(X,syn0))))
  #feed forward with sigmoid activation for Second layer
  l2 = 1/(1+np.exp(-(np.dot(l1,syn1))))
  #Backpropagation of error for second layer of weights with derivative of Sigmoid
  l2_delta = (y - l2)*(l2*(1-l2))
  #Backpropagation of error for first layer of weights with derivative of Sigmoid and the summation
  l1_delta = l2_delta.dot(syn1.T) * (l1 * (1-l1))
  #update of weights in both layers with respective errors from back propagation
  syn1 += l1.T.dot(l2_delta)
  syn0 += X.T.dot(l1_delta)


[[-0.59026371 -0.37370124 -0.9991802   0.55366466]
 [ 0.00968051 -0.60523707 -0.81289141  0.78297085]
 [ 0.56721096 -0.28181779 -0.94492921  0.49197322]]
[[ 0.20243336]
 [ 0.4128774 ]
 [-0.41875505]
 [-0.4776735 ]]
[[-0.59026371 -0.37370124 -0.9991802   0.55366466]
 [ 0.00968051 -0.60523707 -0.81289141  0.78297085]
 [ 0.56721096 -0.28181779 -0.94492921  0.49197322]]
[[ 0.20243336]
 [ 0.4128774 ]
 [-0.41875505]
 [-0.4776735 ]]


In [21]:
Z=[]
for a in range(8):
  Z.append([y[a],z[a]])
Z=np.array(Z)
np.reshape(Z,(8,2))

array([[0, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 1]])

In [22]:
Z

array([[[0],
        [0]],

       [[1],
        [0]],

       [[1],
        [0]],

       [[0],
        [1]],

       [[1],
        [0]],

       [[0],
        [1]],

       [[0],
        [1]],

       [[1],
        [1]]])

In [23]:
c = []
d = []
for a in  X:

      l5 = 1/(1+np.exp(-(np.dot(a,syn0))))
      l6 = 1/(1+np.exp(-(np.dot(l5,syn1))))
      l7 = 1/(1+np.exp(-(np.dot(a,syn3))))
      l8 = 1/(1+np.exp(-(np.dot(l7,syn4))))
      c.append(round(list(l6)[0]))
      d.append(round(list(l8)[0]))
print(c)
if c == list(y) and d==list(z):
  print ('test successful')
else:
  print ('failure')

[0, 1, 1, 0, 1, 0, 0, 1]
test successful


In [24]:
import numpy as np


In [25]:
import numpy as np
X = np.array([[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1] ])
y = np.array([[0,1,1,0,1,0,0,1]]).T
z = np.array([[0,0,0,1,0,1,1,1]]).T
Z=[]
for a in range(8):# making the labels
  Z.append([y[a],z[a]])
Z=np.reshape(Z,(8,2))

syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,2)) - 1

#Neural network with Z variable as target
for j in range(60000):
  #feed forward with sigmoid activation for first layer
  l1 = 1/(1+np.exp(-(np.dot(X,syn0))))
  #feed forward with sigmoid activation for first layer
  l2 = 1/(1+np.exp(-(np.dot(l1,syn1))))
  l2_delta = (Z - l2)*(l2*(1-l2))
  l1_delta = l2_delta.dot(syn1.T) * (l1 * (1-l1))
  syn1 += l1.T.dot(l2_delta)
  syn0 += X.T.dot(l1_delta)
# Neural network with Z variable as target



In [26]:
l4 = 1/(1+np.exp(-(np.dot([1,1,0],syn0))))
l5 = 1/(1+np.exp(-(np.dot(l4,syn1))))
l5

array([0.00583335, 0.98372441])

In [27]:
import numpy as np
X = np.array([[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1] ])
y = np.array([[0,1,1,0,1,0,0,1]]).T
z = np.array([[0,0,0,1,0,1,1,1]]).T
labels=[]
for a in range(8):# making the labels
  labels.append([y[a],z[a]])
labels=np.reshape(labels,(8,2))
# initializing random neurons
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,2)) - 1

#Neural network with Z variable as target
for j in range(90000):
  #feed forward with sigmoid activation for first layer
  b = np.dot(X,syn0)
  l1 = 1/(1+np.exp(-(b)))
  #feed forward with sigmoid activation for first layer
  c = np.dot(l1,syn1)
  l2 = 1/(1+np.exp(-(c)))
  sigmoid_derivatives2 = (l2*(1-l2))
  l2_delta = (labels - l2)* sigmoid_derivatives2
  sigmoid_derivatives1 =(l1 * (1-l1))
  l1_delta = l2_delta.dot(syn1.T) * sigmoid_derivatives1
  syn1 += l1.T.dot(l2_delta)
  syn0 += X.T.dot(l1_delta)