In [ ]:
print("Solution for water jug problem")
x_capacity = input("Enter Jug 1 capacity:")
y_capacity = input("Enter Jug 2 capacity:")
end = input("Enter target volume:")

def Production_Rule_Implementation(start, end, x_capacity, y_capacity):
	path = []
	front = []
	front.append(start)
	visited = []
	#visited.append(start)
	while front:
		current = front.pop()
		x = current[0]
		y = current[1]
		path.append(current)
		if x == end or y == end:
			print("Found!")
			return path
		# rule 1 filling x
		if current[0] < x_capacity and ([x_capacity, current[1]] not in visited):
			front.append([x_capacity, current[1]])
			visited.append([x_capacity, current[1]])

		# rule 2 filling y
		if current[1] < y_capacity and ([current[0], y_capacity] not in visited):
			front.append([current[0], y_capacity])
			visited.append([current[0], y_capacity])

		# rule 3 emptying x
		if current[0] > x_capacity and ([0, current[1]] not in visited):
			front.append([0, current[1]])
			visited.append([0, current[1]])

		# rule 4 emptying y
		if current[1] > y_capacity and ([x_capacity, 0] not in visited):
			front.append([x_capacity, 0])
			visited.append([x_capacity, 0])

		# rule 5 pouring y into x, both in case y is empty or y is left with some
		#(x, y) -> (min(x + y, x_capacity), max(0, x + y - x_capacity)) if y > 0
		if current[1] > 0 and ([min(x + y, x_capacity), max(0, x + y - x_capacity)] not in visited):
			front.append([min(x + y, x_capacity), max(0, x + y - x_capacity)])
			visited.append([min(x + y, x_capacity), max(0, x + y - x_capacity)])

		# rule 6 pouring x into y, both in case x is empty or x is left with some
		# (x, y) -> (max(0, x + y - y_capacity), min(x + y, y_capacity)) if x > 0
		if current[0] > 0  and ([max(0, x + y - y_capacity), min(x + y, y_capacity)] not in visited):
			front.append([max(0, x + y - y_capacity), min(x + y, y_capacity)])
			visited.append([max(0, x + y - y_capacity), min(x + y, y_capacity)])

	return "Not found"

def gcd(a, b):
	if a == 0:
		return b
	return gcd(b%a, a)


start = [0, 0]

if int(end) % gcd(int(x_capacity),int(y_capacity)) == 0:
  	print (Production_Rule_Implementation(start, int(end),int( x_capacity),int( y_capacity)))


else:
	print ("No solution possible for this combination.")

Solution for water jug problem
Enter Jug 1 capacity:21
Enter Jug 2 capacity:87
Enter target volume:18
Found!
[[0, 0], [0, 87], [21, 66], [21, 87], [21, 0], [0, 21], [21, 21], [0, 42], [21, 42], [0, 63], [21, 63], [0, 84], [21, 84], [18, 87]]


In [ ]:
import numpy as np
X = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])
y = np.array([[0,1,1,0]]).T
#initialization
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

for j in range(60000):
  #feed forward with sigmoid activation for first layer
  l1 = 1/(1+np.exp(-(np.dot(X,syn0))))
  #feed forward with sigmoid activation for Second layer
  l2 = 1/(1+np.exp(-(np.dot(l1,syn1))))
  #Backpropagation of error for second layer of weights with derivative of Sigmoid
  l2_delta = (y - l2)*(l2*(1-l2))
  #Backpropagation of error for first layer of weights with derivative of Sigmoid and the summation
  l1_delta = l2_delta.dot(syn1.T) * (l1 * (1-l1))
  #update of weights in both layers with respective errors from back propagation
  syn1 += l1.T.dot(l2_delta)
  syn0 += X.T.dot(l1_delta)


[[ 0.04628291 -0.75591169  0.54223175 -0.11729614]
 [ 0.16687511 -0.12646003 -0.83220527 -0.46744781]
 [-0.97203623 -0.13925011  0.41025516 -0.04732832]]
[[ 0.86436613]
 [ 0.52170591]
 [-0.37675765]
 [-0.46608882]]
[[11.08976102]
 [ 6.78819004]
 [-9.48438653]
 [-4.86318545]]
[[ 5.92261132 -2.12311649  6.6831926  -3.76862944]
 [-6.57322679 -1.16395396 -6.05423118 -4.26342251]
 [-3.07422415  3.18828998  2.8370535   1.18011955]]


In [ ]:
l5 = 1/(1+np.exp(-(np.dot([1,1,1],syn0))))
l6 = 1/(1+np.exp(-(np.dot(l5,syn1))))
print(l6)

[0.00328714]


In [ ]:
import numpy as np
X = np.array([[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1] ])
y = np.array([[0,1,1,0,1,0,0,1]]).T
z = np.array([[0,0,0,1,0,1,1,1]]).T
syn0 = 2*np.random.random((3,4)) - 1
print(syn0)
syn1 = 2*np.random.random((4,1)) - 1
print(syn1)
syn3 = 2*np.random.random((3,4)) - 1
print(syn0)
syn4 = 2*np.random.random((4,1)) - 1
print(syn1)
#Neural network with Z variable as target
for j in range(60000):
  #feed forward with sigmoid activation for first layer
  l1 = 1/(1+np.exp(-(np.dot(X,syn0))))
  #feed forward with sigmoid activation for first layer
  l2 = 1/(1+np.exp(-(np.dot(l1,syn1))))
  l2_delta = (y - l2)*(l2*(1-l2))
  l1_delta = l2_delta.dot(syn1.T) * (l1 * (1-l1))
  syn1 += l1.T.dot(l2_delta)
  syn0 += X.T.dot(l1_delta)
# Neural network with Z variable as target
for k in range(60000):
  #feed forward with sigmoid activation for first layer
  l3 = 1/(1+np.exp(-(np.dot(X,syn3))))
  #feed forward with sigmoid activation for first layer
  l4 = 1/(1+np.exp(-(np.dot(l3,syn4))))
  l4_delta = (z - l4)*(l4*(1-l4))
  l3_delta = l4_delta.dot(syn4.T) * (l3 * (1-l3))
  syn4 += l3.T.dot(l4_delta)
  syn3 += X.T.dot(l3_delta)

  #feed forward with sigmoid activation for first layer
  l1 = 1/(1+np.exp(-(np.dot(X,syn0))))
  #feed forward with sigmoid activation for Second layer
  l2 = 1/(1+np.exp(-(np.dot(l1,syn1))))
  #Backpropagation of error for second layer of weights with derivative of Sigmoid
  l2_delta = (y - l2)*(l2*(1-l2))
  #Backpropagation of error for first layer of weights with derivative of Sigmoid and the summation
  l1_delta = l2_delta.dot(syn1.T) * (l1 * (1-l1))
  #update of weights in both layers with respective errors from back propagation
  syn1 += l1.T.dot(l2_delta)
  syn0 += X.T.dot(l1_delta)


[[ 0.05719951 -0.77194188 -0.6706568   0.01694414]
 [ 0.18365444  0.28363572 -0.31549707  0.58956529]
 [ 0.44812387 -0.24818169 -0.57978359 -0.92466183]]
[[-0.09607308]
 [ 0.46848227]
 [-0.74710276]
 [ 0.13949815]]
[[ 0.05719951 -0.77194188 -0.6706568   0.01694414]
 [ 0.18365444  0.28363572 -0.31549707  0.58956529]
 [ 0.44812387 -0.24818169 -0.57978359 -0.92466183]]
[[-0.09607308]
 [ 0.46848227]
 [-0.74710276]
 [ 0.13949815]]


In [ ]:
Z=[]
for a in range(8):
  Z.append([y[a],z[a]])
Z=np.array(Z)
np.reshape(Z,(8,2))

array([[0, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 1]])

In [ ]:
Z

[array([0]), array([0])]

In [ ]:
c = []
d = []
for a in  X:

      l5 = 1/(1+np.exp(-(np.dot(a,syn0))))
      l6 = 1/(1+np.exp(-(np.dot(l5,syn1))))
      l7 = 1/(1+np.exp(-(np.dot(a,syn3))))
      l8 = 1/(1+np.exp(-(np.dot(l7,syn4))))
      c.append(round(list(l6)[0]))
      d.append(round(list(l8)[0]))
print(c)
if c == list(y) and d==list(z):
  print ('test successful')
else:
  print ('failure')

[0, 1, 1, 0, 1, 0, 0, 1]
test successful


In [ ]:
import numpy as np


In [11]:
import numpy as np
X = np.array([[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1] ])
y = np.array([[0,1,1,0,1,0,0,1]]).T
z = np.array([[0,0,0,1,0,1,1,1]]).T
Z=[]
for a in range(8):# making the labels
  Z.append([y[a],z[a]])
Z=np.reshape(Z,(8,2))

syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,2)) - 1

#Neural network with Z variable as target
for j in range(60000):
  #feed forward with sigmoid activation for first layer
  l1 = 1/(1+np.exp(-(np.dot(X,syn0))))
  #feed forward with sigmoid activation for first layer
  l2 = 1/(1+np.exp(-(np.dot(l1,syn1))))
  l2_delta = (Z - l2)*(l2*(1-l2))
  l1_delta = l2_delta.dot(syn1.T) * (l1 * (1-l1))
  syn1 += l1.T.dot(l2_delta)
  syn0 += X.T.dot(l1_delta)
# Neural network with Z variable as target



In [12]:
l4 = 1/(1+np.exp(-(np.dot([1,1,0],syn0))))
l5 = 1/(1+np.exp(-(np.dot(l4,syn1))))
l5

array([0.00708335, 0.99138983])

In [ ]:
import numpy as np
X = np.array([[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1] ])
y = np.array([[0,1,1,0,1,0,0,1]]).T
z = np.array([[0,0,0,1,0,1,1,1]]).T
labels=[]
for a in range(8):# making the labels
  labels.append([y[a],z[a]])
labels=np.reshape(labels,(8,2))
# initializing random neurons
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,2)) - 1

#Neural network with Z variable as target
for j in range(90000):
  #feed forward with sigmoid activation for first layer
  b = np.dot(X,syn0)
  l1 = 1/(1+np.exp(-(b)))
  #feed forward with sigmoid activation for first layer
  c = np.dot(l1,syn1)
  l2 = 1/(1+np.exp(-(c)))
  sigmoid_derivatives2 = (l2*(1-l2))
  l2_delta = (labels - l2)* sigmoid_derivatives2
  sigmoid_derivatives1 =(l1 * (1-l1))
  l1_delta = l2_delta.dot(syn1.T) * sigmoid_derivatives1
  syn1 += l1.T.dot(l2_delta)
  syn0 += X.T.dot(l1_delta)